name: Docker push
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
          uses: actions/checkout@v2
          
      - name: Build and push Docker images
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: myorg/myrepository
              tags: latest
  
              jobs:
                build:
                  runs-on: ubuntu-latest
                  steps:
                  - uses: actions/checkout@master
                    with:
                      fetch-depth: '0'
                  - name: Bump version and push tag